submitter/.gitignore
submitter/config.sample.js
submitter/package.json
submitter/src/lib/mmr/MMRNode.js
submitter/src/lib/mmr/MMRTree.js
submitter/src/lib/utils.js
submitter/src/mmrSync.js
submitter/src/services/rsk/RskMMR.js
submitter/test/mmr/mmr.test.js
submitter/test/rsk/rskMMR.test.js
submitter/test/services/rsk/rskMMR.test.js
submitter/test/testHelper.js

- Added methods to update mmr tree from rsk blocks
- Backup and restore progress from file
- Serialize/deserialize tree
- Test cases added
Some stats on testnet:
- Total blocks processed on first run: 215285
- Time to sync on first run (aprox): 6 minutes
- Backup file size: 66MB
- Max memory peak (aprox): 380 MB

Build MMRTree from RSK blocks

---

bridge/contracts/Bridge_v0.sol
bridge/contracts/test/Bridge_upgrade_test.sol
bridge/migrations/3_deploy_bridge_v0.js
bridge/test/Bridge_upgrade_test.js
bridge/test/Bridge_v0_test.js

As Ethereum has many testnets we may want to use larger prefix to distinguish them

Use string for symbolPrefix

---

bridge/README.md
bridge/contracts/AllowTokens.sol
bridge/contracts/Bridge_v0.sol
bridge/contracts/IBridge.sol
bridge/contracts/test/Bridge_upgrade_test.sol
bridge/migrations/2_deploy_multisig_and_tokens.js
bridge/migrations/3_deploy_bridge_v0.js
bridge/migrations/4_create_config_file.js
bridge/package.json
bridge/test/AllowTokens_test.js
bridge/test/Bridge_upgrade_test.js
bridge/test/Bridge_v0_test.js
bridge/test/utils.js
bridge/truffle-config.js
federator/.gitignore
federator/config.sample.js
federator/src/abis/Bridge_v0.json

Pass the federation as argument in the Bridge Initialization
The federation is a multisig, we added the creation of the multisig in migrations for simplicity
Rename regtest to rskregtest

Set acceptTransfer to be called only by the federation

---

bridge/contracts/Bridge_v0.sol
bridge/contracts/SideToken.sol
bridge/contracts/SideTokenFactory.sol
bridge/contracts/test/Bridge_upgrade_test.sol
bridge/contracts/zeppelin/upgradable/utils/ReentrancyGuard.sol
bridge/test/Bridge_v0_test.js
bridge/test/SideTokenFactory_test.js
bridge/test/SideToken_test.js

Bridge now can only Mint
Add ReantrancyGuard to acceptTransfer and receiveTokens
Now calbacks for tokens can only be used if crossingPayment  is 0 as they are not payable

Remove Bridge as default operator of SideToken

---

ui/tokenbridge.html

The WETH address from Kovan was not the one used by the majority, so we change it as this is testnet.
Hotjar will give more clarity and feedback on how the users interact with the token bridge Dapp

Fix WETH address and add Hotjar

---

README.md

The tag was moved to a different repository for clearness

Fix Readme url of decentralized repo

---

deploy.sh

Without it, the process keeps in foreground forever, being the only viable options to run it under `tmux` or `screen` or `nohup`. Instead, rely on Docker's first-party support for process supervision.

Add detach flag to `docker run` line

---

ui/index.html

Make rLogin error polymorphic with `Error`
Test case:
1. Open rLogin
2. Click outside rLogin
3. See rLogin error message instead of _undefined_

Fix login error

---

ui/index.html

Upgrades rLogin fixing use of `window.ethereum.send`. See https://github.com/rsksmart/rLogin/releases/tag/v0.1.1

Fix nifty wallet

---

ui/index.html

The login loading wheel do not disappeared when closing WalletConnect modal without connecting.
Implementation:
I don't know why re-trowing makes the UI catch the error, but it seems something in `rLogin.connect` or `isInstalled` Promise are not correctly handled. Not sure if it is an rLlogin bug... added https://github.com/rsksmart/rLogin/issues/38 on rLogin now :) thanks!

Fix loading when web3modal is closed

---

ui/index.html

There was a corner case not addressed by the previous code base. Specifically when a user approved (set her allowance) to a given x.yzw amount, and then tried to cross exact same amount (x.yzw), rounding errors prevented the cross to succeed.

fix for transfers with amount equal to allowance

---

bridge/contracts/AllowTokens.sol
bridge/contracts/Bridge.sol
bridge/contracts/IAllowTokens.sol
bridge/test/AllowTokens_test.js
bridge/test/Bridge_test.js

Following the audit report we will allow any contract to call the bridge.
We will remove the mapping allowedContracts from AllowTokens and won't use checkWhitelisted in the Bridge

Non authorized contracts can call the Bridge

---

.circleci/config.yml
README.md
federator/config/test.local.config.js
federator/integrationTest/integrationTest.js

Add step to run federator integration test in Circle CI pipeline.
Basically runs two local ganache instances, deploys the contracts, runs the test and finally kills off the ganache instances.

Add integration test step in circle CI config

---

federator/integrationTest/transfer.js
federator/src/contracts/AllowTokensFactory.js
federator/src/contracts/BridgeFactory.js
federator/src/contracts/ContractFactory.js
federator/src/contracts/FederationFactory.js
federator/src/lib/Federator.js
federator/src/lib/Heartbeat.js
federator/src/lib/utils.js
federator/test/TransactionSender.test.js
federator/test/web3Mock/eth.js

- Avoid constant creation of new `web3.eth.Contract` objects (related to [this issue](https://github.com/ChainSafe/web3.js/issues/3042))
- Replace `var` with `let`/`const` where appropriate to avoid scope related memory leaks

Attempt at fixing Federator memory leak

---

federator/package-lock.json
federator/package.json
federator/src/lib/Federator.js
federator/src/lib/Heartbeat.js
federator/src/lib/TransactionSender.js
federator/src/lib/utils.js

Gas estimation does not work correctly on RSK and after the London harfork, neither is working on Ethereum
Example https://etherscan.io/tx/0xd30d6cf428606e2ef3667427b9b6baecb2f4c9cbb44a0c82c735a238ec8f72fb
To fix it, we decided to use a hardcoded gas estimation of 250.000
Also Lucas informed me that we got this error
```[2021-08-17T14:44:18.687] [INFO] HEARTBEAT - [event: HeartBeat],[sender: 0x5eb6cECA6BdD82f4a38AAc0b957E6A4B5b1cCEba],[fedRskBlock: 3609052],[fedEthBlock: 13043315],[federatorVersion: 2.0.0],[nodeRskInfo: RskJ/3.0.0/Linux/Java1.8/IRIS-ba01ea2],[nodeEthInfo: Geth/v1.10.6-stable-576681f2/linux-amd64/go1.16.4],[blockNumber: 3609054],[RskBlockGap: 2],[EstEthBlockGap: 1]
[2021-08-17T14:44:18.687] [INFO] HEARTBEAT - Found 9 heartbeatLogs
TypeError [ERR_INVALID_ARG_TYPE]: The …
```

Fix gas estimation harcoding it

---

bridge/contracts/nftbridge/INFTBridge.sol
bridge/contracts/nftbridge/NFTBridge.sol
bridge/test/nftbridge/NFTBridge_test.js
bridge/test/utils.js

Add the possibility to set a fixed when crossing new NFT's
- Set the federation address as `payable`
- Add methods for setting a fixed fee
- Update `receiveTokensTo` to have the possibility of a charge fixed fee and send this fixed value to an federation 
- Enter into the bridge directory and run the truffle test in the file `nftbridge/NFTBridge_test.js` to test the Charge of a fixed fee 
```shell
$~ cd bridge
```
```shell
```
```shell
```
4. Run the test file that calls `receiveTokensTo - Fee`
```shell
$~ truffle test test/nftbridge/NFTBridge_test.js
```

[TBRE-337] Fixed fee NFT

---

abis/Bridge.json
abis/Federation.json
abis/SideToken.json
bridge/contracts/Federation.sol
bridge/contracts/nftbridge/NFTBridge.sol
bridge/test/Federation_test.js
bridge/test/nftbridge/NFTBridge_test.js
bridge/test/utils.js
federator/src/contracts/IFederationV2.js
federator/src/lib/Federator.js
federator/src/lib/utils.js

The federation now will handle just 2 bridges with different interfaces (IBridge and INFTBridge)
- add tests for nft bridge
- Add NFT bridge to Federation contract
- Add doc and comments to variables
- Update Federation tests to have a new bridge 
- Enter into the bridge directory and run the truffle test in the file `test/Federation_test.js`
```shell
$~ cd bridge
```
```shell
```
```shell
```
4. Run the test file that calls `receiveTokensTo`
```shell
$~ truffle test test/Federation_test.js
```

Add NFT Bridge to Federation

---

.circleci/config.yml
bridge/README.md
bridge/package-lock.json
bridge/package.json

- Add coverage step to circleci pipeline (remove Bridge's unit testing phase, since the coverage one already runs those tests)
- Add coveralls' coverage badge to Bridge's README.md
- Fix typo in the Bridge's `deployIntegrationTest` npm script

Add code coverage step to circle CI pipeline, add coveralls dependency

---

bridge/test/nftbridge/FederationV2_to_federation_test.js

- Add tests checking the NFTBridge methods and owner
- Enter into the bridge directory and the tests for the federation test
```shell
$~ cd bridge
```
2. Run all the tests for the Federation upgrade
```shell
$~ npx hardhat test test/nftbridge/FederationV2_to_federation_test.js
```

Add tests for check new methods on federation

---

.dockerignore

```shell
$~ cd bridge
```
```shell
```
```shell
```
4. Run all the tests
```shell
```
- [] Lint is clean `npm run lint`
- [] Test is passing `npm run test`
- [] Contracts are compiling `npm run compile`
- [] Lint is clean `npm run lint`
- [] Test is passing `npm run test`
- [] Typescript is compiling `npm run build`

Removing `./bridge` from `.dockerignore` so the container can be built

---

bridge/abi/NFTBridge.json
bridge/contracts/Bridge/Bridge.sol
bridge/contracts/Federation/Federation.sol
bridge/contracts/Federation/FederationV3.sol
bridge/contracts/nftbridge/INFTBridge.sol
bridge/contracts/nftbridge/NFTBridge.sol
bridge/hardhat/script/createSideNftToken.js
bridge/test/Federation_test.js
bridge/test/nftbridge/NFTBridge_test.js
federator/integrationTest/nftIntegrationTest.js
federator/src/contracts/AllowTokensFactory.ts
federator/src/contracts/BridgeFactory.ts
federator/src/contracts/Constants.ts
federator/src/contracts/FederationFactory.ts
federator/src/contracts/IAllowTokensV0.ts
federator/src/contracts/IAllowTokensV1.ts
federator/src/contracts/IAllowTokensV2.ts
federator/src/contracts/IBridgeNft.ts
federator/src/contracts/IFederationV2.ts
federator/src/contracts/IFederationV4.ts
federator/src/lib/FederatorNFT.ts

Add multichain logic into the NFT contracts, federator, and tests
- Add multichain logic to 
- NFT contracts
- Federator
- Nft Integration tests
```shell
$~ cd bridge
```
```shell
```
```shell
```
```shell
```
```shell
```
```shell
```
7. Run the NFT integration test
```shell
$~ npm run nftIntegrationTest
```
- …

Add multichain logic to NFT Bridge

---

bridge/hardhat/script/tryTxCall.js

Add script to perform a call using the transaction parameters.
This is very helpfull to detect reverted reasons for example if you have https://explorer.rsk.co/tx/0xddcdc5e6917b1f92069fe67585d288b42f1ee11f195597b73e00b206a42d20a3
The script will response
```
npx hardhat run --network rskmainnet ./hardhat/script/tryTxCall.js                       5s
Error: Returned error: VM Exception while processing transaction: revert AllowTokens: Lower than limit
at Object.ErrorResponse (/Users/pedro/git/rsk/tokenbridge/bridge/node_modules/web3-core-helpers/lib/errors.js:28:19)
at /Users/pedro/git/rsk/tokenbridge/bridge/node_modules/web3-core-requestmanager/lib/index.js:302:36
at processTicksAndRejections (node:internal/process/task_queues:83:21) {
```

Add tryCall script to get the revert reason of reverted Tx

---

federator/src/lib/Federator.ts
federator/src/lib/Heartbeat.ts
federator/src/main.ts

Currently the  Heartbeat process trys to emit the heart beat in the blockchain as we are not part of the federation it throws an error and retries 3 times after that the process is shut down.
To fix it prior to this, we should ask if the federator is part of the federation, if it’s not, we should log a warning and skip the rest.
Expected behaviour is that if we are not part of the federation we log a warning and continue syncing without actually calling the bridge or emiting the events.
- Replace the trigger of an error on the heartbeat event emit when the current address is not part of the federation. Instead, give a warning and skip emitting
- Skip running the current chain when the address derivated from the configured pk is not member of the federation
- Run the federator using a pk …

Give a warning when addres is not part of the fed

---

bridge/hardhat.config.js
bridge/hardhat/script/getFederatorMembers.js
bridge/hardhat/script/getSideTokenAddress.js
federator/config/bsctestnet.json
federator/src/contracts/FederationFactory.ts

This PR introduces some improvements on binance support and scripting helpful for troubleshooting
- FederationFactory now returns v2 as the default version, when calling version() gives an error
- Configuration added for the namedAccounts on BSC testnet
- Change the RPC address of the binance host, as the one configured is unresponsive
- Improves scripts:
- getSideTokenAddress: make the script able to run not only for binance but for any network specified.
- getFederationMembers: point to the current Federation contract and not the v2

Small improvements for binance support

---

bridge/.gitignore
bridge/abi/FederationV3.json
bridge/contracts/Federation/FederationV3.sol
bridge/deploy/06_deploy_federation.js
bridge/deploy/07_deploy_federationProxy.js
bridge/deploy/upgrades/02_upgrade_federation.js
bridge/deployed/deployHelper.js
bridge/package.json
bridge/test/AllowTokens_test.js
bridge/test/BridgeV3_to_bridgeV4_test.js
bridge/test/Bridge_upgrade_test.js
bridge/test/Federation_test.js

```shell
$~ cd bridge
```
```shell
```
```shell
```
```shell
```
```shell
```
```shell
```
7. Run the integration test
```shell
```
- [] …

feat: Fixed unit tests and add tests for the new federation version
