rsksmart/tokenbridge

bridge/contracts/RskPow.sol
bridge/test/RskPow_test.js

Check that:
- bitcoinMergedMiningHeader is 80 bytes
- bitcoinMergedMiningHeader hash is lower than RSK target difficulty

Validate Rsk Pow

---

README.md
bridge/README.md
bridge/package-lock.json
bridge/package.json
bridge/test/BlockRecorder_test.js
bridge/test/MMR_test.js
bridge/test/RlpLibrary_test.js
submitter/package.json

Add package.json with rlp in rder to run RlpLibreary_test.js
Update README.md acordingly
In MMR_test compare MMRTree class results with MMR.sol results
Add test for more than 64 blocks and estimated gas
Fix submitters test to run recursively through all the subfolders
Commented console logs to avoid filling the screen with unnecesary data on tests

Small fixes

---

submitter/integrationTest.js
submitter/test/mmrSync.test.js
submitter/test/services/rsk/rskMMR.test.js
submitter/test/testHelper.js

Skip mmrSync test as the process exit cut the other tests

---

.gitignore
bridge/.gitignore
bridge/migrations/2_deploy_contracts.js
bridge/package-lock.json
bridge/package.json
bridge/truffle-config.js
submitter/.gitignore
submitter/config.sample.js
submitter/package.json
submitter/src/lib/CustomError.js
submitter/src/lib/TransactionSender.js
submitter/src/lib/mmr/MMRController.js
submitter/src/services/rsk/RskCreateEvent.js
submitter/src/services/rsk/RskCrossToEth.js
submitter/src/services/rsk/RskMMR.js

Add Testnet configurations to truffle-config.js
Create CustomError for better error handling
Change config.sample.js to use absolute path for mmr file

Fix wrong return at loop in RskCrossEvent

---

README.md
bridge/contracts/MMR.sol
bridge/migrations/2_deploy_contracts.js
submitter/.gitignore
submitter/config.sample.js
submitter/src/abis/MMR.json
submitter/src/lib/mmr/MMRController.js
submitter/src/lib/utils.js
submitter/src/main.js
submitter/src/mmrSync.js
submitter/src/services/rsk/RskCrossToEth.js
submitter/src/services/rsk/RskMMR.js
submitter/test/mmr/mmrController.test.js

Parse to Int values
Add MMR contract initial block
Add last block procesed and store it in submitter/db/lastblock.txt
MMRTree now starts from a config block number

Fix MMR sync add initialBlock to MMR.sol

---

bridge/package.json
bridge/test/EventsProcessor_test.js
bridge/test/MMRProver_test.js
submitter/package.json
submitter/src/lib/TransactionSender.js
submitter/src/services/rsk/RskCrossToEth.js
submitter/transferTest.js

Also fix some minor issues and added test helpers

Fixed gas price because of bad parser

---

.gitignore
bridge/contracts/BlockRecorder.sol
bridge/contracts/MMRProver.sol
bridge/contracts/ReceiptProver.sol
bridge/package.json
submitter/.gitignore
submitter/config.sample.js
submitter/integrationTest.js
submitter/src/lib/TransactionSender.js
submitter/src/main.js

This helps a lot to detect where errors are comming from

Added error message on solidity require

---

bridge/test/MMRProver_test.js
docs/Contracts.md
submitter/config.sample.js
submitter/integrationTest.js
submitter/src/abis/MMRProver.json
submitter/src/lib/mmr/MMRController.js
submitter/src/lib/mmr/MMRTree.js
submitter/src/main.js
submitter/src/services/Scheduler.js
submitter/src/services/rsk/RskCrossToEth.js
submitter/test/mmr/mmrTree.test.js
submitter/transferTest.js

Update submitter MMRProvider Abi
Also enforce confirmations bigger than mmrConfirmations on config.js
MMRTree now returns null when it doesn't find the element
Fixed some spelling mistakes and logging

Update submitter to set MMRProver InitialBlock

---

bridge/contracts/MMRProver.sol
bridge/test/MMRProver_test.js
bridge/test/MMR_test.js
submitter/src/services/rsk/RskCrossToEth.js

Add tests fix RskCrossToEth incorrect initialBlock initialization

Add check in MMrProvider.getBlocksToProve that block is bigger than initialBlock

---

README.md
bridge/migrations/2_deploy_contracts.js
bridge/truffle-config.js
docs/Components.md
docs/Flow.md
submitter/.gitignore
submitter/src/lib/TransactionSender.js
submitter/src/lib/mmr/MMRController.js
submitter/src/services/rsk/RskCreateEvent.js
submitter/src/services/rsk/RskCrossToEth.js
submitter/transferTest.js

Check that previousblock was set before storing it

Update Docs and readme

---

README.md
submitter/src/services/rsk/RskCrossToEth.js

Add documentation link to readme

---

submitter/README.md
submitter/package-lock.json
submitter/package.json

- Installed pm2 (http://pm2.keymetrics.io/)
- Updated npm start command and kept npm run dev without pm2
- Updated README

feature: Add pm2 process manager for self-reboot

---

.gitignore
bridge/contracts/Bridge.sol
bridge/contracts/Transferable.sol
bridge/test/Bridge_test.js
federator/package-lock.json
federator/test/web3Mock/contractMapping.js

Change logIndex from string to uint32

Add missing parameters to Bridge.acceptTransfer in tests

---

federator/src/lib/Federator.js
federator/src/lib/TransactionSender.js

Add retries in case of send Transaction failure, wait 40 seconds between each retrie

Add 3 retries to TransactionSender

---

bridge/contracts/AllowTokens.sol
bridge/contracts/Bridge_v0.sol
bridge/contracts/IBridge.sol
bridge/contracts/test/Bridge_upgrade_test.sol
bridge/test/AllowTokens_test.js
bridge/test/Bridge_upgrade_test.js
bridge/test/Bridge_v0_test.js
bridge/test/utils.js

Both values can be set by the multisig in the AllowTokens contract

Add Daily Limit and minimum tokens limit to cross

---

federator/README.md
federator/transferTest.js

In order to test the transferTest with multiple federators, ensure those federators are part of the owners group of the multisig

Fund federators wallet

---

bridge/contracts/Federation.sol
bridge/test/Federation_test.js

Fix min feds required condition

---

bridge/contracts/Bridge_v0.sol
bridge/contracts/Federation.sol
bridge/package-lock.json
bridge/package.json
bridge/test/Bridge_v0_test.js
bridge/test/Federation_test.js
bridge/truffle-config.js
federator/package.json

Use only 1 call for transactionId in acceptTransfer
Federation reverts transaction if acceptTransfer fails
Add HdWalletProvider to package.json and truffle-config.js

Check the inputs from accept Transfer

---

bridge/migrations/11_create_config_file.js
bridge/package-lock.json
bridge/package.json
bridge/truffle-config.js
federator/.gitignore
federator/config.sample.js
federator/integrationTest.js
federator/package-lock.json
federator/package.json
federator/src/lib/Federator.js
federator/src/lib/TransactionSender.js
federator/transfer.js

Add last block in each network config file
Set truffle-config for testnet deploy
Add pm2 to package.json
Throw on vote failing
Rename transferTest to intergationTest
Remove v from rawTx
Add transfer script

Add requirements

---

README.md
abis/README.md
docs/DappGuide.md
federator/src/lib/TransactionSender.js
ui/tokenbridge.html

Add abis README
Add explorer per network
Fix side token crossing

Fix DappGuide image urls

---

docs/ContractAddresses.md
docs/DappGuide.md
docs/FAQ.md
ui/tokenbridge.html

Add references to testnet dapp as well

Add Navbar links

---

SECURITY.md

Change the bounty program handle name

change bounty program handle

---

federator/src/lib/TransactionSender.js
federator/src/lib/utils.js
ui/tokenbridge.html

- Added dropdown with tokens to cross
- Added List of Tokens
- Reduce the number of calls to the network
- Use login to connect to metamask or nifty following RNS visual
- Use polling instead of awaiting for nifty to respond with the receipt
- Show the steps and they current status when crossing a token

New ui for better usability

---

ui/tokenbridge.html

remove web3 as we sould use window.ethereum as a provder

Fix error message add ehtereum.enabled() back

---

ui/tokenbridge.html

This give an error as currently the mainnet contract doesn't have this method

Fees on mainnet are 0 until we deploy the new version that is already on testnet

---

ui/tokenbridge.html

As users takes its to confirm the transaction on metamask, time we need more than a 30 seconds window if minimum gas price is going up

Use a higher gas on RSK

---

bridge/contracts/Federation_v1.sol
bridge/test/Federation_test.js

Add the corrected check in the Federation constructor.
Add tests for it

Federation members equal or lesser than max member count

---

ui/index.html

Change input type from number to text to avoid browser arrows

Fix fee on mainnet, Fix decimal point for big numbers

---

ui/index.html

Testnet had single collateral DAI, we renamed that to SAI to follow what happened on ethereum and added multicolateral DAI on testnet (Mainnet has multicolateral DAI alone).
Add the option to click the button between the 2 networks, to switch the network, we still need to user to manually change the network from nifty but it is easier for the user to understand

Update SAI and DAI on tesntet, switch network using the button

---

.circleci/config.yml
bridge/.gitignore
bridge/package-lock.json
bridge/package.json
ui/index.html

This should go with https://github.com/rsksmart/rsk-contract-metadata/pull/7

Add RFOX token to the list

---

federator/src/lib/Federator.js
federator/src/services/Scheduler.js
ui/index.html

We will increase the confirmitions needed for mainnet to  be the equivalent of 24 hs

New amount of blocks for confirmations on mainnet

---

deploy.sh
federator/README.md
federator/config/kovan.json
federator/config/rskmainnet.json
federator/config/rsktestnet-kovan.json

First version of secure deployment

Secure deployment

---

ui/index.html

Adds [`@rsksmart/rLogin`](https://github.com/rsksmart/rLogin).
- Keeps compatibility with Metamask and Nifty
- Adds [Wallet Connect](https://github.com/walletconnect)
- Enables to use chains 1 and 30: Ethereum mainnet and RSK Mainet
- UX change: does not prompt wallet automatically
- UI change: header is `position: inherit` now. As far as I manually tested, UI has not changed in desktop nor mobile

Add rLogin

---

federator/src/lib/TransactionSender.js

The price was harcoded to avoid gasestimation error on rsk
The problem is that the firs time it crosses it creates a contract so the first time the gasLimit is really big.
The next transfers are normal, but we where using the limit for the big ones, as gas price goes up the big limit times the high gas price are higher than the balance on the signers throwing a not enough funds
Calculating the gas dinamically and adding a 30% to avoid the estimation error on rsk fixes this issue

Calculate gas price instead of hardcoding it

---

bridge/package-lock.json
bridge/package.json
federator/package-lock.json
federator/package.json
federator/src/lib/TransactionSender.js

This time instead of harcoding the maximum value, we harcode 2 values, the normal transaction and the case of a new token deploy for the first time

Estimation on RSK does not work correctly so we harcoded the values 

---

ui/index.html
ui/txns-storage.js

New functionality splitting approve and cross. Hiding approve button when no necessary.

Approve option removed on enough allowance

---

ui/index.html
ui/txns-storage.js

This branch contains new functionality for displaying previous transactions for the active address (informed via provider).

Txn status on UI

---

ui/index.html

This is the https://bundles.finance/ token

Add rKovBUND token to tokenbridge UI

---

ui/index.html

Oficial web page https://bundles.finance/
On Eth https://etherscan.io/token/0x8D3E855f3f55109D473735aB76F753218400fe96
After crossing to RSK https://explorer.rsk.co/address/0x4991516df6053121121274397a8c1dad608bc95b?__ctab=general

Add BUND token

---

bridge/contracts/AllowTokens.sol
bridge/contracts/Bridge.sol
bridge/contracts/Federation.sol
bridge/contracts/IBridge.sol
bridge/contracts/test/mockReceiveTokensCall.sol
bridge/migrations/20_deploy_allowTokens.js
bridge/migrations/24_deploy_bridge.js
bridge/migrations/25_transfer_federation.js
bridge/package.json
bridge/test/AllowTokens_test.js
bridge/test/Bridge_test.js
bridge/test/Bridge_upgrade_test.js
bridge/test/Federation_test.js
federator/integrationTest/transfer.js
ui/index.html

Include in initialize the vslues of the confirmations
Add more tests to allow tokens
bump bridge version to 2.0.0

AllowTokens: add Confirmations setters and tests

---

bridge/migrations/11_conditional_deploy_mainToken.js
bridge/migrations/30_create_config_file.js
bridge/migrations/4_deploy_erc1820.js
bridge/test/utils.js
bridge/truffle-config.js
federator/.gitignore

Refactor to use only one conditional for local networks
Move the conditional for local networks to utils
Bump the max gasLimit
Add mirrorDevelopment.json to gitIgnore

Fix deployLocalIntegrationTest

---

abis/AllowTokens.json
abis/Bridge.json
bridge/contracts/AllowTokens.sol
bridge/contracts/Bridge.sol
bridge/contracts/IBridge.sol
bridge/migrations/20_deploy_allowTokens.js
bridge/test/AllowTokens_test.js
bridge/test/Bridge_test.js
federator/integrationTest/integrationTest.js

Added mainnet and testnet tokens in the migration deploy

V3 tokens types

---

abis/Bridge.json
abis/Federation.json
bridge/contracts/Bridge.sol
bridge/contracts/Federation.sol
bridge/contracts/IBridge.sol
bridge/contracts/IWrapped.sol
bridge/contracts/Utils.sol
bridge/contracts/test/WRBTC.sol
bridge/contracts/test/mockReceiveTokensCall.sol
bridge/migrations/24_deploy_bridge.js
bridge/migrations/8_deploy_bridge_old.js
bridge/package.json
bridge/test/Bridge_test.js
bridge/test/utils.js

Add WRBTC
Refactor bridge to reduce size
Make receiver address payable

Accept payment in network currency

---

ui/index.html

AMLT token https://etherscan.io/token/0xca0e7269600d353f70b14ad118a49575455c0f2f
Official web page https://amlt.coinfirm.com/
Market cap https://coinmarketcap.com/es/currencies/amlt/
On RSK https://explorer.rsk.co/address/0xff9ea341d9ea91cb7c54342354377f5104fd403f

Add AMLT token to UI

---

abis/AllowTokens.json
abis/Bridge.json
abis/Federation.json
bridge/contracts/AllowTokens.sol
bridge/contracts/Bridge.sol
bridge/contracts/Federation.sol
bridge/contracts/IBridge.sol
bridge/migrations/20_deploy_allowTokens.js
bridge/test/AllowTokens_test.js
bridge/test/Bridge_test.js
bridge/test/Bridge_upgrade_test.js
bridge/test/Federation_test.js
federator/integrationTest/integrationTest.js
federator/src/lib/Federator.js
federator/src/lib/IFederationV1.js
federator/src/lib/IFederationV2.js

Assign TypeId to newly created sideTokens and whitelist them
Modify acceptTransfer and federation voting accordingly
Modify integration test accordingly

Add TypeId to cross event

---

ui/index.html

Bump rLogin to 0.1.2

---

ui/index.html

Bump web3 version
Add fix for USDT as it revert if we want to change the approve value when we have a previous allowance
Remove checkbox "don't ask me again", and always approve for max value

Fix disable approve check not considering decimals

---

abis/AllowTokens.json
bridge/contracts/AllowTokens.sol
bridge/deployed/ethmainnet.json
bridge/deployed/kovan.json
bridge/deployed/rskmainnet.json
bridge/deployed/rsktestnet.json
bridge/migrations/10_transfer_sideTokenFactory_old.js
bridge/migrations/11_conditional_deploy_mainToken.js
bridge/migrations/18_conditional_deploy_mainToken.js
bridge/migrations/19_create_config_file.js
bridge/migrations/20_deploy_allowTokens.js
bridge/migrations/24_deploy_bridge.js
bridge/migrations/25_transfer_federation.js
bridge/migrations/26_transfer_sideTokenFactory.js
bridge/migrations/27_transfer_allowTokens.js
bridge/migrations/30_create_config_file.js
bridge/migrations/8_deploy_bridge_old.js
bridge/migrations/9_transfer_federation_old.js
bridge/package.json
bridge/test/AllowTokens_test.js
bridge/test/Bridge_test.js
bridge/test/Bridge_upgrade_test.js
bridge/test/Federation_test.js
federator/src/contracts/AllowTokensFactory.js
federator/src/contracts/BridgeFactory.js
federator/src/contracts/FederationFactory.js
federator/src/lib/Federator.js
federator/src/lib/utils.js

Add amount confirmations configuration on json network file
Add under 1000 usd limits
Federator use individual retries for simple calls as it gets a lof of JSON RPC ERROR: ""
Create utils.js in Federator

Allow tokens add token types on initialize

---

federator/src/lib/TransactionSender.js

Get multipliyer back to 1.5

---

federator/README.md
federator/config/config.sample.js
federator/package-lock.json
federator/package.json
federator/src/lib/Federator.js
federator/src/lib/TransactionSender.js
federator/src/main.js

Send the signed transaction throw etherscan as well as to the ethereum node
Use Etherscan gas price oracle to avoid gas price too low for transactions or too high

Add Etherscan API to have a fallback option

---

abis/AllowTokens.json
abis/Bridge.json
bridge/contracts/AllowTokens.sol
bridge/contracts/test/mockReceiveTokensCall.sol
bridge/package-lock.json
bridge/package.json
bridge/test/AllowTokens_test.js
bridge/test/Bridge_upgrade_test.js

Change sugested by version 2 Audit
Remove disableAllowedTokensValidation method as well
Update ABIS

Remove isValidatingAllowedTokens as it will never be false

---

bridge/deployed/deployHelper.js
bridge/deployed/ethmainnet.json
bridge/deployed/rskmainnet.json
bridge/migrations/21_deploy_allowTokens.js
bridge/migrations/24_deploy_bridge.js
bridge/migrations/25_transfer_federation.js
bridge/migrations/26_transfer_sideTokenFactory.js
bridge/migrations/27_transfer_allowTokens.js
federator/src/contracts/BridgeFactory.js
federator/src/lib/utils.js

Add 172.17.0.1 as localhost, this ip is used as local host by docker images
Update addresses from the deploy
Add small fixes in the deploy script for mainnet

Add deployed addresses and ip 172.17.0.1 as localhost

---

bridge/migrations/21_deploy_allowTokens.js
federator/integrationTest/integrationTest.js
federator/src/contracts/AllowTokensFactory.js
federator/src/contracts/IAllowTokensV0.js
federator/src/contracts/IAllowTokensV1.js
federator/src/contracts/IBridge.js
federator/src/lib/Federator.js

As we use the original address when we are crossing back we need to get the SideToken address and check against that

Check if the address of the event is the original address

---

bridge/contracts/test/nftbridge/OpenSea721.sol
bridge/contracts/test/nftbridge/OpenSeaEIP712Base.sol
bridge/test/OpenSeaMint_test.js

Example of a Open Sea NFT 721 from https://github.com/ProjectOpenSea/opensea-creatures
And a example of a test using it

Add OpenSea example Contract

---

bridge/contracts/nftbridge/INFTBridge.sol
bridge/contracts/nftbridge/ISideNFTTokenFactory.sol
bridge/contracts/nftbridge/NFTBridge.sol
bridge/contracts/nftbridge/SideNFTToken.sol
bridge/contracts/nftbridge/SideNFTTokenFactory.sol
bridge/contracts/test/nft/NFTERC721TestToken.sol
bridge/package.json
bridge/test/NFTBridge_test.js
bridge/test/SideNFTTokenFactory_test.js
bridge/test/SideNFTToken_test.js

- Add missing data to NFT token creation through new bridge
- Adjust factory and token contracts
- Add unit tests to all affected contracts

Fix createSideNFTToken on NFTBridge

---

bridge/contracts/nftbridge/INFTBridge.sol
bridge/contracts/nftbridge/NFTBridge.sol
bridge/test/Bridge_test.js
bridge/test/Bridge_upgrade_test.js
bridge/test/Federation_test.js
bridge/test/SideToken_test.js
bridge/test/nftbridge/NFTBridge_test.js
bridge/test/utils.js

- Adapt `acceptTransfer` for NFT workflow
- Add unit tests solely for that function

Support acceptTransfer method for NFTs in new bridge

---

bridge/contracts/nftbridge/INFTBridge.sol
bridge/contracts/nftbridge/NFTBridge.sol
bridge/test/nftbridge/NFTBridge_test.js

- Adapts Bridge's claim method to work with ERC721 NFT tokens
- Adds associated unit tests for cross operation (still no cross back - coming in a future PR)

[TBRE-347] Support claim in NFTBridge

---

bridge/contracts/nftbridge/NFTBridge.sol
bridge/contracts/nftbridge/SideNFTToken.sol
bridge/package.json
bridge/test/nftbridge/NFTBridge_test.js

- Burn side NFT tokens on cross back
- Add unit tests for complete cross back flow

[TBRE-347] Burn NFT tokens on cross back

---

bridge/deploy/nftbridge/03_deploy_nftBridgeProxy.js

Creation of NFT side tokens from bridge was not possible without this

Transfer ownership of NFT token factory to NFT bridge on bridge deployment

---

bridge/abi/NFTERC721TestToken.json
bridge/hardhat.config.js
bridge/package-lock.json
bridge/package.json
federator/integrationTest/integrationTest.js

- Refactor integration test for readability and reusability purposes
- Add missing dependencies
- Add missing ABI for NFTERC721TestToken

Refactor federator integration test

---

bridge/abi/AllowTokens.json
bridge/abi/AllowTokensProxy.json
bridge/abi/Bridge.json
bridge/abi/BridgeProxy.json
bridge/abi/Federation.json
bridge/abi/FederationProxy.json
bridge/abi/MultiSigWallet.json
bridge/abi/NFTBridge.json
bridge/abi/SideNFTToken.json
bridge/abi/SideNFTTokenFactory.json
bridge/abi/SideToken.json
bridge/abi/SideTokenFactory.json
bridge/contracts/nftbridge/ISideNFTToken.sol
bridge/contracts/nftbridge/NFTBridge.sol
bridge/contracts/nftbridge/SideNFTToken.sol
bridge/contracts/test/nftbridge/TestTokenCreator.sol
bridge/test/nftbridge/NFTBridge_test.js
bridge/test/nftbridge/SideNFTToken_test.js

Add more tests for NFT bridge
- Remove unused parts of contracts 
- Add unit tests for missing coverages
- Run the integration tests
```shell
$~ cd bridge
```
```shell
```
```shell
```
4. Deploy the contracts to both chains
```shell
$~ npm run deployIntegrationTest
```
```shell
```
6. Run the Integration tests
```shell
```

Add missing contract unit tests

---

federator/config/test.local.config.js
federator/integrationTest/integrationTest.js
federator/integrationTest/nftIntegrationTest.js
federator/src/contracts/AllowTokensFactory.ts
federator/src/contracts/BridgeFactory.ts
federator/src/contracts/ContractFactory.ts
federator/src/contracts/FederationFactory.ts
federator/src/contracts/IAllowTokens.ts
federator/src/contracts/IAllowTokensV0.ts
federator/src/contracts/IAllowTokensV1.ts
federator/src/contracts/IFederation.ts
federator/src/contracts/IFederationV2.ts
federator/src/contracts/IFederationV3.ts
federator/src/lib/Federator.ts
federator/src/lib/FederatorERC.ts
federator/src/lib/FederatorNFT.ts
federator/src/lib/Heartbeat.js
federator/src/lib/config.ts
federator/src/lib/configChain.ts
federator/src/main.js

- Update federator to typescript
- Add `configChain` as a singleton
- Add sidechain as an array of chains 
```shell
$~ cd bridge
```
```shell
```
```shell
```
```shell
```
```shell
```
```shell
```
7. Run the NFT integration test
```shell
$~ npm run nftIntegrationTest
```

Add multichain run to federator

---

bridge/contracts/Bridge/BridgeV2.sol
bridge/test/BridgeV2_to_bridgeV3_test.js

- Add unit test to check the bridge version when updating from v2 to v3
- Add unit test for testing when the users initiate the receiveTokens in the v2 receive one vote of federator v2, we upgrade the contracts to v3 (multichain) and give another federator vote and claim the tokens
```shell
$~ cd bridge
```
```shell
```
```shell
```
4. Go to the federator directory
```shell
$~ cd federator
```
5. Run the federator node
```shell
$~ npm run start-dev
```
```shell
$~ cd bridge
```
```shell
$~ npm run …
```

Unit test deploy multichain

---

Dockerfile
bridge/hardhat/script/isTokenAllowed.js

Change isTokenAllowed script to also bring information and Limits of the token

Get info and limits in isTokenAllowed

---

.aws/task-definition.json
.github/workflows/testnet.yml

```shell
$~ cd bridge
```
```shell
```
```shell
```
```shell
```
```shell
```
```shell
```
7. Run the integration test
```shell
```
- [] …

CD to AWS ECS

---

.github/workflows/testnet.yml

```shell
$~ cd bridge
```
```shell
```
```shell
```
```shell
```
```shell
```
```shell
```
7. Run the integration test
```shell
```
- [] …

Syntax error fixed on testnet workflow

---

federator/README.md
federator/config/config.sample.js

Update federator readme

---

federator/README.md

more documentation

---

Dockerfile

```shell
$~ cd bridge
```
```shell
```
```shell
```
```shell
```
```shell
```
```shell
```
7. Run the integration test
```shell
```
- [] …

Changed dockerfile

---

.github/workflows/slither.yml

- Adds a new slither.yml github-actions workflow. Slither is a solidity static code analyzer for finding security issues in smart contracts. This workflow is configured to run for any changes in the `contracts/` folder. Output of the scan will be available in the [Security > Code Scanning](https://github.com/rsksmart/rif-relay-contracts/security/code-scanning) tab. 
- This is useful for automatically triggering security scans. One use case would be to resolve the security findings reported by the tool prior to a full security audit.  
- Findings are uploaded to the Github Security Page which makes it possible to track the findings more easily. If the finding is marked as false-positive or non-issue, it won't be reported in the subsequent scans and won't be visible in the Github Security …

Slither Github Actions integration

---

.github/workflows/codeql-analysis.yml

Fixed version on codeQL v1 was deprecated.

fix(codeQL): fixed code QL, updated to v2
